services:
  app:
    build: .
    volumes:
      - ./books:/books:ro
      - ./api:/app/public/api:ro
      - ./internals:/app/public/internals:ro
    ports:
      - 8080:8080
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=dev
      - RUST_LOG=${RUST_LOG:-debug}