name: E2E Test

on:
  push: {}
  pull_request: {}
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set up Docker
        uses: docker/setup-docker-action@v5
        with:
          version: latest

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: latest

      - name: Prepare default config
        run: cp config.docker.json config.json

      - name: Start dev compose
        run: docker compose -f docker-compose.dev.yaml up --wait --build

      - name: bun install
        run: bun install
        working-directory: frontend

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          package-manager-cache: false
          working-directory: frontend
          wait-on: 'http://localhost:8080'
        env:
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v7
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v7
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
